graph LR

subgraph "get_broken_streak_habits"
    A[Start] --> B[Initialize broken_streak_habits]
    B --> C[Iterate over habits]
    C --> D[Sort checkpoints by date]
    D --> E[Initialize previous_end_date and streak_broken]
    E --> F[Iterate over checkpoints]
    F --> G[Retrieve start_date]
    G --> H[Check frequency]
    H --> |Weekly| I[Check if streak is broken]
    I --> |Yes| J[Set streak_broken to True and break loop]
    I --> |No| K[Update previous_end_date]
    H --> |Daily| L[Check if streak is broken]
    L --> |Yes| M[Set streak_broken to True and break loop]
    L --> |No| K[Update previous_end_date]
    K --> F
    F --> N[Check if streak is broken]
    N --> |Yes| O[Add habit to broken_streak_habits]
    N --> |No| K
    O --> F
    C --> P[Check if there are more habits]
    P --> |Yes| C
    P --> |No| Q[Return broken_streak_habits]
    Q --> R[End]
end


